### ISSUE TITLE
getContentView 空指针

### ISSUE THREAD

**Issue by siyehua** [cpoopc/ScrollableLayout#4]
```java
<com.cpoopc.scrollablelayoutlib.ScrollableLayout
        android:id="@+id/scrollableLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">
        <RelativeLayout
            android:id="@+id/rl_head"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="#cdcdcd">
        </RelativeLayout>
        <android.support.v4.view.ViewPager
            android:id="@+id/viewpager"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </com.cpoopc.scrollablelayoutlib.ScrollableLayout>

```

我的布局按照上面的布局,ViewPager里面是碎片,碎片实现ScrollableContainer接口
@Override
    public View getScrollableView() {
        return scrollView;
    }
这个方法在返回view的时候,会出现空指针问题.
不是所有的机型都会出现,但是这个错误非常的频繁,这个是我的错误日志

```java
java.lang.NullPointerException
	at com........Fragment.getScrollableView(OddsFragment.java:525)
	at com........view.scrollablelayoutlib.ScrollableHelper.getScrollableView(ScrollableHelper.java:59)
	at com.........view.scrollablelayoutlib.ScrollableHelper.isTop(ScrollableHelper.java:74)
	at com.........scrollablelayoutlib.ScrollableLayout.dispatchTouchEvent(ScrollableLayout.java:185)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2169)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1613)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2539)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2117)
	at android.view.View.dispatchPointerEvent(View.java:8005)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4266)
	

```

其中主要问题是由于 ScrollableHelper.isTop()这个方法出现空指针
原因是ScrollableHelper.getScrollableView()返回的是空.
最后是Fragment.getScrollableView().我具体实现的这个方法,返回的view是空的.
我的具体实现方法是:
```java
@Override
	public View getScrollableView() {
		return scrollView.getContentView();
	}
```

这个ScrollView是使用这个开源框架做的
https://github.com/chrisbanes/Android-PullToRefresh

我想问的是,是不是因为我这个ScrollView.getContentView()还没有得到内容,而你的框架已经调用了getScrollableView这个方法,才导致这个问题的

**Comment by cpoopc** [comment]
可能是ScrollableHelper.setCurrentScrollableContainer(scrollView)传入的scrollView与界面中显示的scrollView不是同一个内存对象,多次inflate布局的时候,获得的控件是多个对象,这个需要注意下.
没有代码,我也只是觉得有可能是这个原因.

**Comment by siyehua** [comment]
@cpoopc 根据你说的不是同一个对象,我终于查到到了大概的原因.
我的ViewPager中有五个碎片,其中三个是通过ScrollView.getContentView的方法来实现getScrollableView()这个方法的.
我发觉.另外两个根布局本身就是一个listview,我直接返回了,就没有这个问题.
而出现问题的这三个ScrollView其实本身是一个容器来的,并不是一个可滚动的View,所以我通过ScrollView.getContentView()这中方式返回一个可以供滚动的View.

也就是我设置的时候
ScrollableHelper.setCurrentScrollableContainer(parentView);
而实现这个的时候
```java
@Override
    public View getScrollableView() {
        return scrollView.getContentView();//child view
    }
```
只是不知道为何这样子不行.难道碎片的根布局是一个可滚动的View吗?
我观察你的碎片根布局也不是一个ScrollView
但是我碎片在创建的时候,直接new 出一个view来,这样会有问题吗?
```java
@Override
	@Nullable
	public View onCreateView(LayoutInflater inflater,
			@Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
		myTipsScrollView = new MyTipsScrollView(mContext);

		return myTipsScrollView;
	}
```

**Comment by cpoopc** [comment]
```
@Override
    @Nullable
    public View onCreateView(LayoutInflater inflater,
            @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        if(myTipsScrollView==null){
                myTipsScrollView = new MyTipsScrollView(mContext);
        }

        return myTipsScrollView;
    }
```
改成这样试试看
